language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=3.1.5
  global:
  - secure: Gc1eD8iGpax5JFtMPxi6cWbm+Whe7KAdxTKE/btDUJo8e/H8UzDQwRzo5YWaS4X6RrlLfrSij0tlO4Qq4fFDl1rhMLwdw33aeEnbYqg/gA7owmXfk1UfG5+WfkEG5y0eB0ze+ghDkdiugC/hIQXpMLpmpHutOUuNEKoXZToEQJ90Bky0TOv6QoVFawsf8Kg3bcEaeVGWcv1ynWmVUGPLgBDm5vMFGmXt0fVw0bJp8hvjIiFg8KTENfOY2rvtLz1SwqdXxfEbCm5J/OZsIX4dR8PTVyQfwMO2QPnLq5pwRRxwgOx1usJQVyxhMy7hykNBQXW2FbpUOqT9/Oa/fAhmHNSWm7KEN7yJR1HCc8cHu6yJbNK26XMc1HZT3w3CE9z34TeFd0UAHHzfdNW0nM5Zr7ChBV5qxKHSZ2qXbF6HdT41zU1+/UnqA010Jnltonum6/9cfCS9UiKdkSbX2eq2Fa5EYO1qEuKm9J2DsC7Asj0p7KwIXX1oEVjEDyjl4JTsZhol1v+zRLHZMFQu8rleR43OLWEfDRG6y9UGiOJh9IRL2RlPKhm3g7RFki+0965VANdpV4IdS1LYU30iJjmFQEc8O0kS0LHEKZYSaJkPZzRC8jxbedy5V87gZxo2d0NP4flmRgGE1507zc9x9z29o8d1b3b+P4CVFNQlpLOQvho=
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  on:
    branch: main
  provider: heroku
  app: portfolio-heikura
  api_key:
    secure: kt1BpaqgF44rST6vmWVaYEYizZmUe3iGs+FJdXK5CiXq7IBZNvwgYm1l3vTRuBjeHzyILaibiFQ0jaUt0MJqhLdBNnbQntGH4Wl9dKVjXLZLNIgALJOd+cSz0vpclNHlgIEqHrMJ1BBM313VrubeCKRY3sXiyPz8julQuM7yKfj0kKhasN+GNYOfD3Pt5e5UTzzeNr2VKh/51pK4jWQfcVoFltUB4zGqZ7MJqjKpFH38AIBfahDWuQqE+puRt9RWWQI+N2qjj65j7gMteN2XrwKve6+8HnUJxEOeWzPt+okGiWzf7qGgn8K7JeMrQKmkodsbBTwAjGrAw3SMc3IdijyTZt315LQwUatZ1kDRI3Sl3qLWpu0D/jHM4NSTL2kwVNHZ/jcll/Udq25HFJ18AVjQIFP7ZaZFwq9z6pDXPTIaNToi02bSb4J17+B4HWRRbCRTh+toU6uzQ5la1En0kmDy538eayVK3JgQyE27VT5A5Zob7ctIAWqnbzINQKBd+0JoApWEF6IEZKWV+SWlQEF9aXsbBxQCFhl+dcYl/jRo4gd34+mnlb9oFPvf6VITXbfCvaD8kup+UGxTXlnHusZD4f4h9KiYNJVdonPlhSvZzu813gzhIeVGK70GcGP2GoG/SUETpnWJrGAPLlOMUyJNrwnbQGWIykM9pIMdzzs=
