language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=3.1.5
  global:
    secure: Gc1eD8iGpax5JFtMPxi6cWbm+Whe7KAdxTKE/btDUJo8e/H8UzDQwRzo5YWaS4X6RrlLfrSij0tlO4Qq4fFDl1rhMLwdw33aeEnbYqg/gA7owmXfk1UfG5+WfkEG5y0eB0ze+ghDkdiugC/hIQXpMLpmpHutOUuNEKoXZToEQJ90Bky0TOv6QoVFawsf8Kg3bcEaeVGWcv1ynWmVUGPLgBDm5vMFGmXt0fVw0bJp8hvjIiFg8KTENfOY2rvtLz1SwqdXxfEbCm5J/OZsIX4dR8PTVyQfwMO2QPnLq5pwRRxwgOx1usJQVyxhMy7hykNBQXW2FbpUOqT9/Oa/fAhmHNSWm7KEN7yJR1HCc8cHu6yJbNK26XMc1HZT3w3CE9z34TeFd0UAHHzfdNW0nM5Zr7ChBV5qxKHSZ2qXbF6HdT41zU1+/UnqA010Jnltonum6/9cfCS9UiKdkSbX2eq2Fa5EYO1qEuKm9J2DsC7Asj0p7KwIXX1oEVjEDyjl4JTsZhol1v+zRLHZMFQu8rleR43OLWEfDRG6y9UGiOJh9IRL2RlPKhm3g7RFki+0965VANdpV4IdS1LYU30iJjmFQEc8O0kS0LHEKZYSaJkPZzRC8jxbedy5V87gZxo2d0NP4flmRgGE1507zc9x9z29o8d1b3b+P4CVFNQlpLOQvho=
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  on:
    branch: main
  provider: heroku
  api_key:
    secure: WhCE2P/PodsP+giIDIQDfOZ+L2TuNyhsd8gYllIi44AbuKFiPaNe9OkujlyQhSlL9bsNMdqf0fSH5o8bcvz2LOUlt7aHdmgPZ3/o5ivdoScVEBroGJ2gcWEI1V1BMfg6IUInK83jEOLIuB/2xW8WOkAGEeycImoboZSfjyoJcHbkTsXksL/WDU90Gp+BxcfvsCpY4p7Xg/5Y4vE/WywhzrA9/pNICaPJ/vEJcHDeLoNRmcqmKF6HYINhFatDDt5TDuhcV2Oyu6XIyIiGz237pASk6tXgilLxlwtQshmtrITJJ5idXIWlxKP3E/MWRwGpt9t3b6k1T4ysbDKfOoklxeYXgFRyJCR74gL2uPnjKF3n6UHWZYNdwY7pXm1BtsFEGSRESWM6C62PDK8mQkP8gIdFoEpxNJ+PDxNfRfiZa4H1TSyv5LjJIRy+ptRBc9XvPOgcuSAQ/TGQIjN3BKeusmm7rGqKem8JaMfx6Rv6eq83SiSy1251TJYlpK8Y7uct7Y4Iqb7fSeUpn+nwiQSCvZ02RB6kAFQf+LQoKhPE0G2jrldqsAw2Kf0reGaPx2/QSqqiv9sLdF2Z7B3J2XwKzmV9q2nDhMnWLmEZdULWf0csfSRBr2Vj8RNXdWml9IyHIG3oa/hT/+VE9zssmAkaBDBbI4f5bqT4myrbXwJDceM=
