language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=3.1.5
  global:
    secure: FKMlxQZrAgIA4mUAo0/cK2BOGNMwdPd6rJJctaK99J6rSqCyUzR6iUZZ0m8YdyP7RaT6Tl7vPLmWeDhPaYntp5LcGNjbVpJDFeLpxlCgYHs+c8Bb5jHSfLN/tZmO1G12fonJAMkYVEkceVVD/9KC/4IFY2xATQiWTm6FeEbtyO2uKhwvYlLFplc873qkjxQEWY2rlkn4qL4o1obl4GW15K2SR0Hpw2i48MQ4K+oCAQywEeR881nktxTnUSwg92d2LfS0O0nU/DPL4nUU1s8lYcbmPDi9nJ1By736LQV+Bh5delBbBRRu1IUd/8Nmhq7iXkpu7TJO0DW20ObcGZAgYfOi8siTJhuWMz/84RcXDVJvJKtx7PomFpxho0cbmpjbkuNpB1zG/BiHp1Yr2cZgMY5DmYuxlmp548JVAPFFeVf+dgGMpH/7HJhdjLcfn5/NMUDwoXTCtFVu2KuDytNdoubGkCOajkLHLaYRmINvxc6CdGa799MvJNyX0fynz5RPm1RuscVHT3uKQtRJBUrqbbLuWmWZ8tt1r2uvrBeLCxaqYq4BbuA5uWByicX/vapEQpMwnhza+p5wiWCOLa3W4m5x4DtlR7DTgMQPDURrS3PronqYF8rSTdfPA5Nwm8wY1R1Dv84fnGsABLf3987VOVXo3SW4M+tQhH3s+oKZPtA=
install:
- pip install -r requirements.txt
script:
- python manage.py tests
deploy:
  api_key:
    secure: 41oSylSzuIETkcOiju0Sj/dpfBDthg30TbzimK/BOvnN1HCi/q+VlMKjf1EgNBpNAhoyd7GpI+uTjBw/S0D5drN8T0H7z+FPCmdH9Y7lplnin4LT8RVsZKBnzdP9B+fKqwu2dLPOvOEmvr36HRLm2FztPzZDN3fFkGEANM/qhRC9Rz/1e0Uiqlpf2qoGdzyFs6379cmgBNQ06erkUxxHr+xIfOKd89B7zuK9dk7z7UshT9pZapoaL/Ce1Nvt5VeSpDfUx3swwtu4VXYU4SZrsfwevfzOD/tu//dIkzJmAGwLxNXehovr9kVkcc1nPaN+178X7nYRkIxnuc9wijFaMXQmRyOX1mkCdp97C0QFenZT97SvN0EH5Zxwtn/R4LKqfomKyCYaYWxYlQRa9ltShfKfw8j7Lf6eh14mkPee+XWBxAh2XAOsIjvM5gbnbdSNY/c8+yulkVXhJBlP9ACPmxwnoROVBc3EHW2vlx2h5/JXqE8JAd9XNXpvt6CE9atm3V2HPfY+TPant5qFK/8qDHmCH4PU8vj4GxamRceg6Eg680egO46Vvo4RMrzbI/yXHU8Yy2TjcPKM6d4dvp7GEaf5d/anML+eBjeeFbJ7P042XV9939TsdaQKt5VK+sDuFqVXHAOA6SF0v1YVidPEfLG51udwxDC1lGheGvF9e/Q=
