language: python
python:
- '3.7'
env:
- DJANGO_VERSION=3.1.5
  -secure: "bMgmQLQmwIULOYhTct0uXJym3RcseNliot6Qwe0yWZ+N9NV50xOVA6YG27vZmisvoVr8N3fFDoJdTTQcilncFEpTj6+D0J1H3DuW3L6ElGr17zDSzBEth6q2VXKei8PPUmyU6UyyxUOmIVCVpWmsX5QVm/NTscACKcPzWePNwQ8SjEP5K8tnwZL7jzp84apvYnO8+fc47zfTxgoTDyWvesnlTKLNE+G0207+cD5U3XAJTIv9Vi3dTySoG+b//GLvQSFcai33xkS/bZ9fHrOcMX/r6yQWQu4ly1bid6//T8e6aJeXbhK4nnETeiFFP5sdpX902Wy34wIWBEJco2tJiswT3LcLaxxhHIEX7wxPNPXa0kLN1yfh+i+2CdkFfzDCVYQ+ijELobTMK1vVJdA2hSAjIjAS3FS3xKHrVz+T72fRXZMWI+R0wNs8ZyNhkZtb/RPGquDNgbUtLcFolMhstncg+S7g3cvheH9n3vySy6Sd1xgukYr3WLYd4Spx/aJTlzLqh6g/aI+HcBFoQbGCiaWk6m0PjxubFTofLTR20QcbPvOuWY5WnWhK2N8Ezd8XGMu6qtShXCy/MNB7KSF5WmxZQlz2jd1hLTCwCGO2MB3J4ABkdw+AEIIuqpSSsw4sOyaIB6FnRv73vNXMUitP8bRYdNoIMyBp8lmHkUQo4Zs="
install:
- pip install -r requirements.txt
script:
- python manage.py tests
deploy:
  api_key:
    secure: 41oSylSzuIETkcOiju0Sj/dpfBDthg30TbzimK/BOvnN1HCi/q+VlMKjf1EgNBpNAhoyd7GpI+uTjBw/S0D5drN8T0H7z+FPCmdH9Y7lplnin4LT8RVsZKBnzdP9B+fKqwu2dLPOvOEmvr36HRLm2FztPzZDN3fFkGEANM/qhRC9Rz/1e0Uiqlpf2qoGdzyFs6379cmgBNQ06erkUxxHr+xIfOKd89B7zuK9dk7z7UshT9pZapoaL/Ce1Nvt5VeSpDfUx3swwtu4VXYU4SZrsfwevfzOD/tu//dIkzJmAGwLxNXehovr9kVkcc1nPaN+178X7nYRkIxnuc9wijFaMXQmRyOX1mkCdp97C0QFenZT97SvN0EH5Zxwtn/R4LKqfomKyCYaYWxYlQRa9ltShfKfw8j7Lf6eh14mkPee+XWBxAh2XAOsIjvM5gbnbdSNY/c8+yulkVXhJBlP9ACPmxwnoROVBc3EHW2vlx2h5/JXqE8JAd9XNXpvt6CE9atm3V2HPfY+TPant5qFK/8qDHmCH4PU8vj4GxamRceg6Eg680egO46Vvo4RMrzbI/yXHU8Yy2TjcPKM6d4dvp7GEaf5d/anML+eBjeeFbJ7P042XV9939TsdaQKt5VK+sDuFqVXHAOA6SF0v1YVidPEfLG51udwxDC1lGheGvF9e/Q=
