language: python
python:
- "3.7"

env:
- DJANGO_VERSION=3.1.5
- DJANGO_SECRET_KEY

# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python manage.py tests
