language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=3.1.5
  global:
  - secure: Gc1eD8iGpax5JFtMPxi6cWbm+Whe7KAdxTKE/btDUJo8e/H8UzDQwRzo5YWaS4X6RrlLfrSij0tlO4Qq4fFDl1rhMLwdw33aeEnbYqg/gA7owmXfk1UfG5+WfkEG5y0eB0ze+ghDkdiugC/hIQXpMLpmpHutOUuNEKoXZToEQJ90Bky0TOv6QoVFawsf8Kg3bcEaeVGWcv1ynWmVUGPLgBDm5vMFGmXt0fVw0bJp8hvjIiFg8KTENfOY2rvtLz1SwqdXxfEbCm5J/OZsIX4dR8PTVyQfwMO2QPnLq5pwRRxwgOx1usJQVyxhMy7hykNBQXW2FbpUOqT9/Oa/fAhmHNSWm7KEN7yJR1HCc8cHu6yJbNK26XMc1HZT3w3CE9z34TeFd0UAHHzfdNW0nM5Zr7ChBV5qxKHSZ2qXbF6HdT41zU1+/UnqA010Jnltonum6/9cfCS9UiKdkSbX2eq2Fa5EYO1qEuKm9J2DsC7Asj0p7KwIXX1oEVjEDyjl4JTsZhol1v+zRLHZMFQu8rleR43OLWEfDRG6y9UGiOJh9IRL2RlPKhm3g7RFki+0965VANdpV4IdS1LYU30iJjmFQEc8O0kS0LHEKZYSaJkPZzRC8jxbedy5V87gZxo2d0NP4flmRgGE1507zc9x9z29o8d1b3b+P4CVFNQlpLOQvho=
  - secure: riDgtvq7myAB9eRsDhV66Z2A6xwblvtry4CL+ehaH02O4W2xnKmpn6lEnAIsraGWeaIOYyN3x/SQUNobTYkdp4h3hEqn2W6EKsfWml8f9GlsUad69HhmzK+DZSrTAY6ogtD+P7/O/vgf67g9g8cRhCsiC+xPL2q51j/qwIRkOW0H9tHChNAm6TYqqRxCtX7zXouyREee6Dxa1XB1h0uzOZfKMs5ak74sYufxOzWiKqlRsSW/+co8FfzNiO1AfAaizeNKRvf7IpTFx0IyiKQwUwbnruNI0vK04JCOLfjBm+SAIIiEmRmd8AeN1Ya+8HjntQLT5np1FWVOccpLE60ZDrEAp1ULAGOCRUlhT8cmcbEN0YnCkcmVCc6lR8ra/hPVt+qhS6P8+kTVGIP/F517+ZA/w/Gtb57CWXB5OF5OljzrH6+Vorf726zhk0foR9+LBMMd1NBrfUj/OGqIh1gVE8mZT0TUyZ/TIuk0D/U5VDDEHMLGNuUVFgaRUsQC1iBlNXr4OYvs05r94+co1uK6J34xigCCzL6tEkhUaxSEh6Syo+fXqBXTo0NFupR+1cxINpnEtwtLuGGLwkCv9DgGFp0EdaPoRaiafmn75RRnxyYuxov+fCdFecvxmeNnkHOOyY1hzqsyekyAV32Kd3+6NYBn5Udz1IDHGC/KSP4siAw=
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  on:
    branch: main
  provider: heroku
