language: python
python:
- '3.7'
env:
  matrix:
  - DJANGO_VERSION=3.1.5
  global:
  - secure: IphBSAjn8dQDOJl6LvJSe9yAo0oyuOP6pbUiOUkOjLR5SUkAjiVmRbLj4JOC3qtrasTYN81IV+RJYpgRzaQL3PYtS9OQ+kTwnmQKNS47SaArYeA9ViSHmjBRD+kLrEnXqOaxuE6S5Dw1Ob3YEnx5vznSP3TE9V+wPFgEusQ5n6g1c5z3Pk62uC9g3oiUohQ9LkUopFIq29ykgDiSUV5yERCLEpyvN2YmbEszm66qC/s5T6hfsMu7XZHgl9k+uhfkg/RYccXe3+BmR0knlUUoSyAn9khzWGyE+JOgDWkdMCiqWKyh7+qg25Cu1ZWaREzFhd7yto2m3lutR7DinzSJMBYfZ4Jivi6gSM+E308gOYomU8jEu36bdh/kCQ5YL+xsOaOx2caF+JMkgLjQUIYhTANDHFQfRghI5wdz0awVGAlAIsNHjcgKwXpoQpn1AoGqYYQw7rIraG/ahP7P1GacUgW27VIHwUN9eC7alezUmInqnSoQhTH1TBE8gxoCRlm8JvYPPE0/b/1fhSSQFt3G/LkvCxyuYuDTNlr05+uBoTSNrG9suhUcJfKnmM/NdFQfz/ZppSh/ec5HsIU87oXek/3q7nUda11eaL/MfWmupEjxmSZv5Rwcs2vaZE1ajXuk7K6CuDOmlxbUCdPaFSO8j0ZAF83eT3067Bq3sVTn7MM=
install:
- pip install -r requirements.txt
script:
- python manage.py tests
deploy:
  api_key:
  - secure: 41oSylSzuIETkcOiju0Sj/dpfBDthg30TbzimK/BOvnN1HCi/q+VlMKjf1EgNBpNAhoyd7GpI+uTjBw/S0D5drN8T0H7z+FPCmdH9Y7lplnin4LT8RVsZKBnzdP9B+fKqwu2dLPOvOEmvr36HRLm2FztPzZDN3fFkGEANM/qhRC9Rz/1e0Uiqlpf2qoGdzyFs6379cmgBNQ06erkUxxHr+xIfOKd89B7zuK9dk7z7UshT9pZapoaL/Ce1Nvt5VeSpDfUx3swwtu4VXYU4SZrsfwevfzOD/tu//dIkzJmAGwLxNXehovr9kVkcc1nPaN+178X7nYRkIxnuc9wijFaMXQmRyOX1mkCdp97C0QFenZT97SvN0EH5Zxwtn/R4LKqfomKyCYaYWxYlQRa9ltShfKfw8j7Lf6eh14mkPee+XWBxAh2XAOsIjvM5gbnbdSNY/c8+yulkVXhJBlP9ACPmxwnoROVBc3EHW2vlx2h5/JXqE8JAd9XNXpvt6CE9atm3V2HPfY+TPant5qFK/8qDHmCH4PU8vj4GxamRceg6Eg680egO46Vvo4RMrzbI/yXHU8Yy2TjcPKM6d4dvp7GEaf5d/anML+eBjeeFbJ7P042XV9939TsdaQKt5VK+sDuFqVXHAOA6SF0v1YVidPEfLG51udwxDC1lGheGvF9e/Q=
